name: procurator
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9
  - biopython
  - pandas
  - pyrodigal         # Python interface for Prodigal
  - pyhmmer           # Python interface for HMMER
  - bcbio-gff         # For GFF3 file I/O